### ISSUE TITLE
shows only part of text

### ISSUE THREAD

**Issue by RollinSafary** [koreezgames/phaser3-i18n-plugin#2]
if you've
```
const value: number = 123456
const text:string = `any string: ${value}`
```
using` text`  in creating text object will show only text after `:`

`const textObject = this.add.text(0, 0, text)`
result is ` 123456`

if we remove `:` from string, everything works

```
const value: number = 123456
const text:string = `any string ${value}`
```

**Comment by saqsun** [comment]
@RollinSafary this issue is not related to this plugin.
You should move this issue to the https://github.com/i18next/i18next repo

**Comment by RollinSafary** [comment]
[issue ](https://github.com/i18next/i18next/issues/1064)in https://github.com/i18next/i18next,
answer: https://www.i18next.com/overview/configuration-options
I think it's mean that, there is a need to configure plugin :D

**Comment by saqsun** [comment]
So that is simple just change nsSeparator in config ;)
```
create () {
  this.i18n.initialize(
    {
      fallbackLng: 'en',
      loadPath: 'assets/i18n/{{lng}}/{{ns}}.json',
      debug: false,
      nsSeparator: '$'
    },
    function () {
      console.log('I18nPlugin initialized!')
    },
  )
}
```
